In [1]:
import torch
import torchvision
import torchtext
import torchaudio

print(torch.__version__)
print(torchvision.__version__)
print(torchtext.__version__)
print(torchaudio.__version__)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

2.0.1+cpu
0.15.2+cpu
0.15.2+cpu
2.0.2+cpu


'cpu'

# Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(7)
7
0


In [3]:
# Vector
vector = torch.tensor([7,9])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 9])
1
torch.Size([2])


In [4]:
# Matrix
matrix = torch.tensor([
                        [7,8],
                        [9,10]
                      ])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[0])
print(matrix[1])


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([7, 8])
tensor([ 9, 10])


In [5]:
# Tensors
tensor = torch.tensor([[[1,2,3],
                       [3,4,5],
                       [6,7,8]]])
                       
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0])

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])


In [6]:
#RANDOM Tensors
random_tensor = torch.rand(2,6,3)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor[0])

tensor([[[0.0968, 0.8569, 0.3956],
         [0.5718, 0.1963, 0.4176],
         [0.9427, 0.6887, 0.3958],
         [0.2244, 0.4652, 0.7829],
         [0.6279, 0.9709, 0.9443],
         [0.5015, 0.3458, 0.6269]],

        [[0.7248, 0.7626, 0.5409],
         [0.6766, 0.0755, 0.3666],
         [0.6298, 0.0542, 0.0376],
         [0.5998, 0.6465, 0.7281],
         [0.3225, 0.8287, 0.6599],
         [0.3514, 0.2815, 0.5109]]])
3
torch.Size([2, 6, 3])
tensor([[0.0968, 0.8569, 0.3956],
        [0.5718, 0.1963, 0.4176],
        [0.9427, 0.6887, 0.3958],
        [0.2244, 0.4652, 0.7829],
        [0.6279, 0.9709, 0.9443],
        [0.5015, 0.3458, 0.6269]])


In [7]:
# ONES, ZEROS, ARANGE
ones = torch.ones(2,3)
# print(ones)
zeros = torch.zeros(3,4)
# print(zeros)
one_to_thousand = torch.arange(start=0,end=1000,step=5)
# print(one_to_thousand)
zeros_like = torch.zeros_like(input=one_to_thousand)
# print(zeros_like)
print(one_to_thousand.dtype)
# print(one_to_thousand)

torch.int64


In [8]:
# dtype, device, requires_grad, pin_memory
zero_to_thousand = torch.arange(start=0,end=1000,step=5)

# dtype
# print(zero_to_thousand.dtype)
# converted_tensor = zero_to_thousand.type(torch.float) # can also be supplied as dtype= during tensor creation
# print(converted_tensor.dtype)
# print(converted_tensor)

# device
# print(zero_to_thousand.device)
# converted_tensor = zero_to_thousand.to(device) # can also be supplied as device= during tensor creation
# print(converted_tensor.device)

# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=device, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float64, device(type='cpu'))

# Tensor Operations

In [9]:
# Tensor operations
# addition, subtraction, elem-wise mult, division are done element-wise
tenny = torch.tensor([1,2,3])

print(tenny + 10) # same as torch.add()
print(tenny + torch.tensor([10])) # same as torch.add()
print(tenny + torch.tensor([10,20,10])) # same as torch.add() these two tensors must match in dim 0
print()
print(tenny - 10) # same as torch.sub()
print(tenny - torch.tensor([10])) # same as torch.sub()
print(tenny - torch.tensor([10,20,10])) # same as torch.sub()
print()
print(tenny * 10) # same as torch.mul()
print(tenny * torch.tensor([10])) # same as torch.mul()
print(tenny * torch.tensor([10,20,10])) # same as torch.mul()
print()
print(tenny / 10) # same as torch.div()
print(tenny / torch.tensor([10])) # same as torch.div()
print(tenny / torch.tensor([10,20,10])) # same as torch.div()
print()
print(tenny // 7) # same as torch.floor_divide()
print(tenny // torch.tensor([10])) # same as torch.floor_divide()
print(tenny // torch.tensor([10,20,10])) # same as torch.floor_divide()


tensor([11, 12, 13])
tensor([11, 12, 13])
tensor([11, 22, 13])

tensor([-9, -8, -7])
tensor([-9, -8, -7])
tensor([ -9, -18,  -7])

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([10, 40, 30])

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.1000, 0.3000])

tensor([0, 0, 0])
tensor([0, 0, 0])
tensor([0, 0, 0])


In [10]:
print(torch.matmul(tenny, tenny)) # equivalent to dot product equivalent to tensor @ tensor
# Create two 2D tensors of shapes (3, 4) and (4, 5)
A = torch.randn(3, 4)
B = torch.randn(4, 5)

C = torch.matmul(A, B)
C = A @ B
C = A.matmul(B)

print(C.shape)
print(C)

# Create two 3D tensors of shapes (2, 3, 4) and (2, 4, 5)
A = torch.randn(2, 3, 4) #(B1, M, N)
B = torch.randn(2, 4, 5) #(B2, N, P)

# Perform batched matrix multiplication
C = torch.matmul(A, B) #(max(B1, B2), M, P) If B1 and B2 are not equal, and none of them is 1, you will get a size mismatch error. 
C = torch.bmm(A, B) #(max(B1, B2), M, P) If B1 and B2 are not equal, and none of them is 1, you will get a size mismatch error. 

print(C.shape)
print(C)

tensor(14)
torch.Size([3, 5])
tensor([[ 1.6582,  2.6346,  1.9378,  1.2950, -4.2695],
        [-0.9646, -2.3584, -0.5811,  1.6182,  2.0142],
        [-0.8814, -0.1755,  1.9099, -2.7449,  2.2097]])
torch.Size([2, 3, 5])
tensor([[[-2.8773,  3.6855, -0.4120, -1.2367, -0.1421],
         [ 0.8001,  5.7781,  3.7129, -1.3995, -2.8679],
         [-1.7364,  0.3754, -1.5317, -0.1240,  0.7024]],

        [[-0.1214, -0.7844,  0.4186, -0.9060,  0.3738],
         [ 0.5406, -0.9285,  0.0581,  0.4693,  1.2101],
         [ 2.8592, -1.4266, -0.6189, -3.9236,  1.6685]]])


In [11]:
# Transpose

# A = torch.randn((3,5))
# print(A.shape)
# print(A)
# A_T = torch.transpose(A,0,1) # equivalent to A.T
# print(A_T.shape)
# print(A_T)

# A = torch.randn((3,5,2,3))
# print(A.shape)
# # print(A)
# A_T = torch.transpose(A,0,1)
# print(A_T.shape)
# # print(A_T)
# A_T = torch.transpose(A,0,2)
# print(A_T.shape)
# # print(A_T)

A = torch.randn((2,3,4))
print(A.shape)
print(A)
A_T = torch.transpose(A,0,1)
print(A_T.shape)
print(A_T)
A_T = torch.transpose(A,0,2)
print(A_T.shape)
print(A_T)

torch.Size([2, 3, 4])
tensor([[[ 1.3610,  0.3154, -1.5615, -0.3373],
         [-0.3074, -0.3590,  0.3805,  0.1832],
         [ 0.7051,  1.0087,  0.2206, -0.8162]],

        [[-0.4327,  0.0604, -0.4278, -0.7020],
         [-0.1862,  0.5522, -1.4698,  1.1582],
         [ 0.8324,  1.0840,  0.3081,  0.3766]]])
torch.Size([3, 2, 4])
tensor([[[ 1.3610,  0.3154, -1.5615, -0.3373],
         [-0.4327,  0.0604, -0.4278, -0.7020]],

        [[-0.3074, -0.3590,  0.3805,  0.1832],
         [-0.1862,  0.5522, -1.4698,  1.1582]],

        [[ 0.7051,  1.0087,  0.2206, -0.8162],
         [ 0.8324,  1.0840,  0.3081,  0.3766]]])
torch.Size([4, 3, 2])
tensor([[[ 1.3610, -0.4327],
         [-0.3074, -0.1862],
         [ 0.7051,  0.8324]],

        [[ 0.3154,  0.0604],
         [-0.3590,  0.5522],
         [ 1.0087,  1.0840]],

        [[-1.5615, -0.4278],
         [ 0.3805, -1.4698],
         [ 0.2206,  0.3081]],

        [[-0.3373, -0.7020],
         [ 0.1832,  1.1582],
         [-0.8162,  0.3766]]])


In [12]:
# min,max,mean,sum
A = torch.arange(1,100,5)
print(A)
print(torch.min(A))
print(torch.max(A))
print(torch.mean(A.type(torch.float64)))
print(torch.sum(A))
print()

# min,max,mean,sum for multi-dim tensors
A = torch.arange(1,100,5).reshape((4,5))
print(A)
print(torch.min(A,dim=1))
print(torch.max(A,dim=0))
print(torch.mean(A.type(torch.float64),dim=1))
print(torch.sum(A,dim=-1))
print()

# argmin,argmax,mean,sum for multi-dim tensors
A = torch.arange(1,100,5).reshape((4,5))
print(A)
print(torch.argmin(A,dim=1))
print(torch.argmax(A,dim=0))
print(torch.mean(A.type(torch.float64),dim=1))
print(torch.argsort(A,dim=-1))

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])
tensor(1)
tensor(96)
tensor(48.5000, dtype=torch.float64)
tensor(970)

tensor([[ 1,  6, 11, 16, 21],
        [26, 31, 36, 41, 46],
        [51, 56, 61, 66, 71],
        [76, 81, 86, 91, 96]])
torch.return_types.min(
values=tensor([ 1, 26, 51, 76]),
indices=tensor([0, 0, 0, 0]))
torch.return_types.max(
values=tensor([76, 81, 86, 91, 96]),
indices=tensor([3, 3, 3, 3, 3]))
tensor([11., 36., 61., 86.], dtype=torch.float64)
tensor([ 55, 180, 305, 430])

tensor([[ 1,  6, 11, 16, 21],
        [26, 31, 36, 41, 46],
        [51, 56, 61, 66, 71],
        [76, 81, 86, 91, 96]])
tensor([0, 0, 0, 0])
tensor([3, 3, 3, 3, 3])
tensor([11., 36., 61., 86.], dtype=torch.float64)
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


In [26]:
# reshaping, viewing, stacking, spliting, squeeze, unsqueezing, permute, transpose
A = torch.arange(0,100,10)
print(A.reshape((2,5))) # reshaping becomes shape 2,5
print(A.view((5,2))) # reshaping becomes shape 5,2 but does not change the original A
print(torch.stack((A,A,A,A,A,A,A),dim=0)) # concat rows same as torch.vstack
print(torch.stack((A,A,A,A,A,A,A),dim=1)) # concat cols
print(torch.vstack((A,A,A,A,A,A,A))) # concat rows
print(torch.hstack((A,A,A,A,A,A,A))) # concat rows
B = torch.randn((2,3,4))
C = torch.dstack((B,B,B)) # Stack tensors in sequence depthwise (along third axis).
print(C.shape)
A = torch.zeros((2,1,3,4,2))
print(torch.squeeze(A).shape) # Returns a tensor with all specified dimensions of input of size 1 removed.
print(torch.unsqueeze(A,dim=3).shape) # Returns a new tensor with a dimension of size 1 inserted at the specified position.
print(torch.permute(A,(2,4,0,1,3)).shape) # Returns a view of the original tensor input with its dimensions permuted.

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])
tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])
tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
tensor([[ 0,  0,  0,  0,  0,  0,  0],
        [10, 10, 10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40, 40, 40],
        [50, 50, 50, 50, 50, 50, 50],
        [60, 60, 60, 60, 60, 60, 60],
        [70, 70, 70, 70, 70, 70, 70],
        [80, 80, 80, 80, 80, 80, 80],
        [90, 90, 90, 90, 90, 90, 90]])
tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10,

In [27]:
# indexing and slicing
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor)
element = tensor[1, 2]  # Access the element at row 1, column 2
print(element)
sub_tensor = tensor[1:3, 1:3]  # Access the sub-tensor from row 1 to 2 and column 1 to 2
print(sub_tensor)
print(tensor[2,1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(6)
tensor([[5, 6],
        [8, 9]])
tensor(8)


In [ ]:
# Putting tensors into device and getting them out. e.g numpy does not work with gpus
A = torch.randn((60000,768)).to(device)
print(A)
A.cpu().numpy()
